version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/src:/app/src
      - /app/node_modules
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=development
    command: npm run dev
